services:
  redis:
    image: redis:6.2-alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
  
  api_server:
    build:
      context: .
      dockerfile: api_server.Dockerfile
    container_name: api_server
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - redis
  
  worker:
    build:
      context: .
      dockerfile: worker.Dockerfile
    container_name: worker
    restart: always
    depends_on:
      - redis

  test_runner:
    build:
      context: .
      dockerfile: api_server.Dockerfile
    container_name: test_runner
    command: ["pytest"]
    depends_on:
      - redis
